### PR TITLE
Added addons: horses2foam

### PR DESCRIPTION
**Pull request by hmarbona**
This addons convert .hsol to foam format in Paraview. Doesnt change the core part of the code

### CODE REVIEW

**Comment by Andres-MG** [comment]
Should we add this to the docs?

**Comment by loganoz** [comment]
If I understand correctly, @hmarbona, you copied the sources of horses2plt to create this new add-on. That means that if new functionalities were added to horses2plt, these would need to be added manually to horses2foam, right?

**Comment by hmarbona** [comment]
Correct, the outputVariables module was modified from horses2plt, so new function needs to be added manually

**Comment by loganoz** [comment]
@hmarbona, what's the status of this pull request?

**Comment by hmarbona** [comment]
I havent worked to combine it. I will try to do it this week, shouldnt take much time.

**Comment by hmarbona** [comment]
This pull request can be closed as it has been accommodated by other request.

**Pull request closed without merging**
